# Generated by Django 5.1.6 on 2025-02-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "type_contact",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("collectivite", "Collectivité"),
                            ("visiteur", "Visiteur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
